<?php

namespace GCF\MainBundle\Repository;

/**
 * ActeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeurRepository extends \Doctrine\ORM\EntityRepository
{
    public function topBySector($SecteurActeur)
    {
        $Acteurs = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a')
            ->from('GCFMainBundle:Acteur', 'a')
            ->leftJoin('a.secteurActeur', 'sa')
            ->Where('sa.id = :secteur')
            
            ->setParameter('secteur', $SecteurActeur->getId())          //      )       //  
            //->setMaxResults(5)
            ->getQuery()
            ->getResult();
            //->getSingleScalarResult();
        
        return $Acteurs;
    }
    public function search($keyword, $nb = 50){
        $Acteurs = $this->getEntityManager()
            ->createQueryBuilder()
                ->select('a')
                ->from('GCFMainBundle:Acteur', 'a')
                ->where('a.nom LIKE :key')
                ->orWhere('a.nomcomplet LIKE :key')
                ->orWhere('a.description LIKE :key')
                ->orWhere('a.mission LIKE :key')
                ->orWhere('a.responsable LIKE :key')//$adresse
                ->orWhere('a.emailresponsable LIKE :key')
                ->orWhere('a.telresponsable LIKE :key')
                ->orWhere('a.contact LIKE :key')
                ->orWhere('a.adresse LIKE :key')
                ->orWhere('a.email LIKE :key')
                ->orWhere('a.tel LIKE :key')
                ->orWhere('a.fax LIKE :key')
                ->orWhere('a.siteweb LIKE :key')

                ->setParameter('key' , '%'.$keyword.'%')
                ->setMaxResults($nb)
                ->orderBy('a.id', 'DESC')
                ->getQuery()
                ->getResult();
        return $Acteurs;
    }
}
