<?php

namespace GCF\MainBundle\Repository;

/**
 * ActualitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualitesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast3Actualities(){

        $actualities = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('GCFMainBundle:Actualites', 'p')
            ->where('p.etatPub = 2')
            ->setMaxResults(3)
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult();

        return $actualities;
    }

    public function findRelatedNews(){

        $relatedNews = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('GCFMainBundle:Actualites', 'p')
            ->where('p.etatPub = 2') //etat pub Public '2' -> id de publique dans la bdd
            ->setMaxResults(3)
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult();

        return $relatedNews;
    }

}
