<?php

namespace GCF\MainBundle\Repository;

/**
 * ConcentrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcentrationRepository extends \Doctrine\ORM\EntityRepository
{
}
