<?php

namespace GCF\MainBundle\Repository;

/**
 * ElearningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElearningRepository extends \Doctrine\ORM\EntityRepository
{
    public function findlast($nb, $catid){

        $nosEvent = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('e')
            ->from('GCFMainBundle:Elearning', 'e')
            ->where('e.catLearning = :cat')
            ->setParameter('cat', $catid)
            ->setMaxResults($nb)
            ->orderBy('e.id', 'DESC')
            ->getQuery()
            ->getResult();

        return $nosEvent;
    }
}
