services:
#    gcf_front.example:
#        class: GCF\FrontBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }